/setpoint_sequence_node:
  ros__parameters:
    setpoints: true #follow setpoints [false] (1.2.1) or follow color_tracker [true] (1.2.2, 1.2.3)
    mode: true #true, for /moving_camera (1.2.3), false, for /image (1.2.2) [must also change remap]
    width: 240
    desired_width: 100.0 # width of tracked object in frame
    #[duration, x, y, z ]
    setpoints_array: [
      10.0, 0.0, 0.0, 0.0,
      10.0, 1.0, 0.0, 0.0,
      10.0, 2.0, 2.0, 0.0,
      10.0, 0.0, 0.0, 0.0,
      2.0, 0.0, 0.0, 0.0
    ]
    #
